name: cinder
description: A tinder for cats
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter_bloc: ^8.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqlite3: ^2.1.0
  sqflite: ^2.0.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  assets:
    - .env
    - assets/CinderLogo.png
  uses-material-design: true
