name: cinder
description: A tinder for cats
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter_bloc: ^8.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqlite3: ^2.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  assets:
    - .env
    - db.sqlite3
  uses-material-design: true
